run-name: "06-secrets-variables - ${{ github.actor }}"

on:
  workflow_dispatch:

jobs:
  secret-check:
    name: Environment Variable
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Skript ausführbar machen
        run: chmod +x scripts/*.sh

      - name: Skript 06_env_config starten
        run: bash scripts/06_env_config.sh
        env:
          APP_NAME: ${{ vars.NORDSTERN_APP_NAME }}
          RELEASE_VERSION: ${{ vars.NORDSTERN_RELEASE_VERSION }}
          DEPLOY_ENV: ${{ vars.NORDSTERN_STAGE }}
        
      - name: Erfolgsmeldung anzeigen
        if: success()
        run: echo "Release Pipeline war erfolgreich."

      - name: Fehlermeldung anzeigen
        if: failure()
        run: echo "Release Pipeline ist fehlgeschlagen"

      - name: Abschlussmeldung anzeigen
        if: always()
        run: echo "Pipeline wurde beendet. Dieser Step läuft immer."


      - name: Skript 07_secret_check starten
        run: bash scripts/07_secret_check.sh
        env:
          NORDSTERN_API_TOKEN: ${{ secrets.NORDSTERN_API_TOKEN }}

      - name: Report-Config-Summary als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: output/config-summary.txt

      - name: Report-secret-check als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: secret-report
          path: output/secret-check.txt